language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: kwasniewski.mateusz@gmail.com
  api_key:
    secure: DVm2AS3AO4MOGRTUUznkRNGYIjhYRQBWQYsFqRxFEix57kA1zSr5eHe01yl1zVFss0pCyd/hu4ZhsB2ZmH60PGEYCV1y3vXNPjvv7k6y4AHmBPQ4SICBg+IePwrYiowDXtodIF313kf9e9XX3Yo5DN61VWwFS3u7R2H0Cff9v2o=
  on:
    tags: true
    repo: Schibsted-Tech-Polska/express-tracing
